[tool.poetry]
name = "graphqlient"
version = "0.0.1a1"
description = ":)"
authors = ["Vojtěch Dohnal <vojdoh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
gql = {extras = ["aiohttp"], version = "^3.1.0"}
Jinja2 = "^3.1.1"
inflection = "^0.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

